name: kompani
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#808080'
    - '#555555'
    - '#d5d5d5'
  brandStrength: 0.25
  lightness: 0.5471136362757534
  saturation: 0.25
  rhythmicContrast: 0.9969846250023693
purpose: []
