name: kompani
favicon: null
layout_spectrum: 0.7340293030720204
typography_spectrum: 0.5428272269200534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17733797966502607
  lightness: 0.5471136362757534
  saturation: 0.3317729621194303
  rhythmicContrast: 0.9969846250023693
purpose: []
